<!-- <h2>Hello	World</h2> -->
<?php  $_gridrecords = $block->getCollection(); // get collection which we set in block class ?>
<?php if ($_gridrecords && count($_gridrecords)): ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?php echo __('Booking Details') ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?php echo __('ID #') ?></th>
                    <th scope="col" class="col name"><?php echo __('Name') ?></th>
                    <th scope="col" class="col name"><?php echo __('Gender') ?></th>
                    <th scope="col" class="col purpose"><?php echo __('Purpose') ?></th>
                    <th scope="col" class="col date"><?php echo __('Booking Date') ?></th>
                    <th scope="col" class="col status"><?php echo __('Is Bookable') ?></th>
                    <th scope="col" class="col ">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php  // read collection as magento1.x and display in list 
                       foreach ($_gridrecords as $_gridrecord): ?>
                    <tr>
                        <td class="col id"><?php echo $_gridrecord->getId() ?></td>
                        <td class="col shipping"><?php echo $_gridrecord->getName() ?></td>
                        <td class="col shipping"><?php echo $_gridrecord->getGender() ?></td>
                        <td class="col shipping"><?php echo $_gridrecord->getPurpose() ?></td>
                        <td class="col date"><?php echo $block->formatDate($_gridrecord->getBookingDate()) ?></td>
                        <td class="col status"><?php echo $_gridrecord->getIsBookable() ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); // for display pager block which we create in block file.   ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?php echo __('grid records not available.'); ?></span></div>
<?php endif ?>
